package labs;

import java.util.Random;

public class DNAGenerator_TestAICode {
	/*Prompt given to ChatGPT: 
	 * "Write code in Java to print to the console 1,000 randomly generated DNA 3 mers (e.g. “ACA”, “TCG” ) 
	 * where the frequency of the nucleotides are p(A) = 0.12, p(C) = 0.38, p(G) = 0.39 and p(T) = 0.11" 
	 * 
	 * The following code was generated by ChatGPT based on the prompt:
	 */
	
	// Function to generate a nucleotide based on given probabilities
    public static char generateNucleotide(Random rand) {
        double randomValue = rand.nextDouble();
        if (randomValue < 0.12) {
            return 'A';
        } else if (randomValue < 0.12 + 0.38) {
            return 'C';
        } else if (randomValue < 0.12 + 0.38 + 0.39) {
            return 'G';
        } else {
            return 'T';
        }
    }

    // Function to generate a random 3-mer
    public static String generate3Mer(Random rand) {
        StringBuilder threeMer = new StringBuilder(3);
        for (int i = 0; i < 3; i++) {
            threeMer.append(generateNucleotide(rand));
        }
        return threeMer.toString();
    }

    public static void main(String[] args) {
        Random rand = new Random();
        String sequence = "";
        for (int i = 0; i < 1000; i++) {
        	/*editing code to assign generate3Mer(rand) to a variable
        	 * And add it to a main sequence to test conditions
        	 */
            String codon = generate3Mer(rand);
            sequence = sequence + codon;
            System.out.println(codon);
        }
        System.out.println(sequence);
        System.out.println(sequence.chars().filter(ch -> ch == 'A').count());
        System.out.println(sequence.chars().filter(ch -> ch == 'C').count());
        System.out.println(sequence.chars().filter(ch -> ch == 'G').count());
        System.out.println(sequence.chars().filter(ch -> ch == 'C').count());
        System.out.println(sequence.length());
    }
}

//Testing the code generated by ChatGPT

